// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIxMNgsvssA1glr18nZKNzZer5-jIsQ9Q',
    appId: '1:890269824365:web:c59d5ddc0d012ed742d664',
    messagingSenderId: '890269824365',
    projectId: 'randevu-cepte-c040d',
    authDomain: 'randevu-cepte-c040d.firebaseapp.com',
    storageBucket: 'randevu-cepte-c040d.firebasestorage.app',
    measurementId: 'G-JY03W99QVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6h1fwmNUz-lBIGCBeMq59jf6ki4PDelQ',
    appId: '1:890269824365:android:2e36a814f0e2094c42d664',
    messagingSenderId: '890269824365',
    projectId: 'randevu-cepte-c040d',
    storageBucket: 'randevu-cepte-c040d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdM-8yZAG6GmUOcP-j_57x6rwHsPrTRIY',
    appId: '1:890269824365:ios:6a8015c99f354dd242d664',
    messagingSenderId: '890269824365',
    projectId: 'randevu-cepte-c040d',
    storageBucket: 'randevu-cepte-c040d.firebasestorage.app',
    iosBundleId: 'com.example.randevuCepte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdM-8yZAG6GmUOcP-j_57x6rwHsPrTRIY',
    appId: '1:890269824365:ios:6a8015c99f354dd242d664',
    messagingSenderId: '890269824365',
    projectId: 'randevu-cepte-c040d',
    storageBucket: 'randevu-cepte-c040d.firebasestorage.app',
    iosBundleId: 'com.example.randevuCepte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIxMNgsvssA1glr18nZKNzZer5-jIsQ9Q',
    appId: '1:890269824365:web:ff3a944f2089e00042d664',
    messagingSenderId: '890269824365',
    projectId: 'randevu-cepte-c040d',
    authDomain: 'randevu-cepte-c040d.firebaseapp.com',
    storageBucket: 'randevu-cepte-c040d.firebasestorage.app',
    measurementId: 'G-EWY6SY00DB',
  );
}
